// src/routes/condicao-pagamento/novo/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import CondPagForm from '$lib/components/forms/cond-pag-form.svelte';

  let { data } = $props();

</script>

<h1 class="font-semibold text-3xl mb-10" >Criar Nova Condição de Pagamento</h1>

<CondPagForm {data} />


<a href="/condicao-de-pagamento">Voltar</a>

// src/app/condicoes-pagamento/novo/page.tsx
import { Separator } from "@/components/ui/separator";
import PaymentConditionForm from "../form";
import { fetchActivePaymentMethods } from "@/lib/data/formas-pagamento";

export default async function NewPaymentConditionPage() {
  const paymentMethods = await fetchActivePaymentMethods();

  return (
    <div className="form-container">
      <div>
        <h1 className="text-2xl font-bold">Nova Condição de Pagamento</h1>
      </div>
      <Separator className="my-6" />
      <PaymentConditionForm paymentMethods={paymentMethods} />
    </div>
  );
}
